module.exports = {
  AppointmentModel: require("./appointment"),
  ColorModel: require("./color"),
  CommonPermissionModel: require("./commonPermission"),
  CustomerModel: require("./customer"),
  CostomerAndUserMode: require("./customerAndUser"),
  FleetModel: require("./fleet"),
  InspectionModel: require("./inspection"),
  LabelModel: require("./label"),
  LabourModel: require("./labour"),
  MessgeChatModel: require("./messagechat"),
  MessageTemplate: require("./messageTemplate"),
  OrderModel: require("./order"),
  OrderStatusModel: require("./orderStatus"),
  PartModel: require("./parts"),
  PaymentRecordModel: require("./paymentRecord"),
  PlanModel: require("./plan"),
  PriceMatrixModel: require("./priceMatrix"),
  RateStandardModel: require("./paymentRecord"),
  RoleModel: require("./role"),
  ServiceModel: require("./services"),
  SMSModel: require("./smsData"),
  TierModel: require("./tier"),
  TimeClockModel: require("./timeClock"),
  TransactionModel: require("./transaction"),
  UploadModel: require("./upload"),
  UserModel: require("./user"),
  UserActivityModel: require("./userActivity"),
  VendorModel: require("./vendor"),
  VehicleModel: require("./vehicle"),
  VendorCommonObjectModel: require("./vendorCommanObject"),
  HomePageModel: require("./homePage"),
  SettingsModel: require("./siteSetting"),
  FaqModel:require("./faq")
};
